version: "3"

name: banking

services:
  banking:
    build:
      context: "./"
      dockerfile: "Dockerfile"
    container_name: banking
    volumes:
      - ./:/opt/www
    ports:
      - 9501:9501
    depends_on:
      - valkey
    environment:
      - SCAN_CACHEABLE=false

  valkey:
    container_name: banking-valkey
    image: valkey/valkey:bookworm
    ports:
      - 6379:6379

  zipkin:
    image: openzipkin/zipkin
    container_name: banking-zipkin
    ports:
      - 9411:9411

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: banking-prometheus
    command: [ "--config.file=/prometheus/prometheus.yml" ]
    volumes:
      - ./observability/prometheus:/prometheus
    ports: 
      - 9090:9090

  grafana:
    image: grafana/grafana:10.4.4
    container_name: banking-grafana
    restart: unless-stopped
    environment:
      - TERM=linux
    ports:
      - 3000:3000
    volumes:
      - ./observability/grafana:/var/lib/grafana

  db:
    hostname: db
    container_name: banking-database
    image: postgres:15.4
    environment:
      POSTGRES_DB: database
      POSTGRES_PASSWORD: postgre
      POSTGRES_USER: postgre
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgre -d database"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 40s