version: "3"

name: transactions

services:
  web:
    build:
      context: "./"
      dockerfile: "Dockerfile"
    container_name: transactions
    volumes:
      - ./:/var/www/
    tty: true
    ports:
      - 9501:9501
    depends_on:
      - valkey
    restart: always

  valkey:
    container_name: valkey-queue
    image: valkey/valkey:bookworm
    ports:
      - 6379:6379

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin-transactions
    ports:
      - 9411:9411

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: prometheus-transactions
    command: [ "--config.file=/prometheus/prometheus.yml" ]
    volumes:
      - ./observability/prometheus:/prometheus
    ports: 
      - 9090:9090

  grafana:
    image: grafana/grafana:10.4.4
    container_name: grafana-transactions
    restart: unless-stopped
    environment:
      - TERM=linux
    ports:
      - 3000:3000
    volumes:
      - ./observability/grafana:/var/lib/grafana

  db:
    hostname: db
    container_name: database-transactions
    image: postgres:15.4
    environment:
      POSTGRES_DB: database
      POSTGRES_PASSWORD: postgre
      POSTGRES_USER: postgre
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgre -d database"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 40s