name: CI with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install JQ Tool
        uses: mbround18/install-jq@v1

      - name: Run Docker container
        run: docker compose up -d

      - name: Wait up hyperf application
        run: sleep 30

      - name: Run Integration Tests
        run: /bin/bash ./test/integration_test.sh
