name: CI with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Docker container
        run: docker compose up -d

      - name: Wait up hyperf application
        run: sleep 15

      - name: Run Integration Tests
        run: ./integration_test.sh
