name: CI for Hyperf Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-php:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP with required extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: pcov, swoole

      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer

      - name: Install Dependencies
        run: composer install

      - name: Run Tests
        run: composer test

      - name: Check Code Style
        run: composer cs-check

      - name: Static Analysis
        run: composer analyze
